# Generated by Django 4.0.5 on 2022-06-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_villians'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Villians',
            new_name='Villian',
        ),
    ]
